### ISSUE TITLE
Inversion only sticks for a few seconds

### ISSUE THREAD

**Issue by wilmcontreras** [zoltanp/xrandr-invert-colors#12]
Have the same problem with xcalib as well: colors become inverted, but after a few seconds, they return to normal (seemingly randomly: once it lasted 2 seconds, another time 3, and another one 6 seconds). I think it's a similar issue as [this one](https://github.com/zoltanp/xrandr-invert-colors/issues/11).

When I run with -d, I only get "debug output enabled,' no other messages.

I'm on Ubuntu 16.04, Intel® HD Graphics 530 (Skylake GT2), with "X.Org X server -- Intel i8xx, i9xx display driver" (not sure if this is the right info).

**Comment by koo5** [comment]
this is kinda what happens when i have redshift running. it changes the screen hue every few moments and resets the inversion setting

**Comment by wilmcontreras** [comment]
Wooo! You were right: RedShift was causing the problem! And it makes perfect sense, it just didn't occur to me because in OS X, I had flux and screen inversion simultaneously.

**Comment by zoltanp** [comment]
koo5 : thanks for answer and solving this issue :-)

**Comment by koo5** [comment]
happy i could help
