### ISSUE TITLE
Not working on Ubuntu 17.10

### ISSUE THREAD

**Issue by marcelogranja** [zoltanp/xrandr-invert-colors#15]
It was working fine on Ubuntu 17.04, but this change after updating.

Worse, no error message is provided. Any clue?

**Comment by zoltanp** [comment]
I only have some questions for now: your session on Ubuntu 17.10 is running
on Wayland or on Xorg? I don't know which one is the default. This program
only works on Xorg, AFAIK.

Also what kind of GPU do you have in your system, and which driver do you
use?

Redshift, or equivalent program is not running in the background, which
might adjust the colors of your display, overriding the inverted colors?

**Comment by koo5** [comment]
"On supported systems, Wayland is now the default display server. The older display server is still available: just choose Ubuntu on Xorg from the cog on the log in screen. "
https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes

**Comment by zoltanp** [comment]
​So the default is Wayland on 17.10. This could be a source for the issue.
Thanks for looking it up.

(And on Ubuntu 18.04, Xorg will be the default :
https://insights.ubuntu.com/2018/01/26/bionic-beaver-18-04-lts-to-use-xorg-by-default/
)
