### ISSUE TITLE
Reverts back to normal after 3 seconds

### ISSUE THREAD

**Issue by TealG** [zoltanp/xrandr-invert-colors#16]
Works for about 3 seconds, then the screen reverts back to normal.
Xorg 1.19.5
`-d` does not print any debug output

**Comment by TealG** [comment]
Never mind, redshift was running in the background that caused this issue.
After stopping redshift it works.
Strangely though `xcalib` works even while redshift is running.

**Comment by TealG** [comment]
Would be a good idea to mention this in the README, since I see now several closed issues about this.

**Comment by zoltanp** [comment]
Done, added section to readme.
​
