### ISSUE TITLE
way to query if colours are currently inverted

### ISSUE THREAD

**Issue by korakinos** [zoltanp/xrandr-invert-colors#19]
Is there a way to query the current state of xrandr-inverted-colors (i.e. if the colours are currently inverted or not) from a script?

Reason: I am using a script to change my desktop background colour whenever xrandr-invert-colors is called, because I want my background to always be dark, colours inverted or not. Currently my script creates or deletes, respectively, a temporary file ("~/.cache/colors-inverted") every time it is called, and sets the background to dark in one case light in the other. This works most of the time, except if for some reason the file sticks around or gets deleted by error (e.g. if I power down the computer with colours inverted); then I end up with a glaring bright background.

**Comment by koo5** [comment]
hope this helps https://github.com/koo5/xrandr-invert-colors/commit/55597b17b621cd9a0dc58a3b756e3d006b43a36d

**Comment by korakinos** [comment]
Hey, that's very nice, thank you! I have realised by now (if I'm right…) that it wouldn't make sense for xrandr-invert-colors to store the "state of invertedness". Other tools can modify the gamme ramps as well, so there is no easy distinction between "inverted" and "not-inverted". 

That said, the patch you provided would work very well – thanks again. However, it made me think that I could just as well query the colour of my desktop background[0] and invert it dynamically. So after all, no changes to xrandr-invert-color are necessary, let's keep it simple.

[0] using `xfconf-query`in the case of the XFCE desktop environment

**Comment by zoltanp** [comment]
It should be possible to write an utility that empirically detects if the ramma ramps are inverted or not (the R, G, B values in earch ramp should be non-decreasing if the ramps is non-inverted, and non-increasing if it is inverted), but it will be hard to cover all possible cases, and the output of the program should be "not inverted" or "inverted" or "unknown" or "error"...

If it is ever needed, I would implement that as a separate executable.

I'm glad that you have found a workable solution by reusing existing programs.

I'm leaving this issue as closed, just adding this comment for discussion / archiving.
