### ISSUE TITLE
Feature request: support vnc on remote computer

### ISSUE THREAD

**Issue by QiangF** [zoltanp/xrandr-invert-colors#26]
When xrandr-invert-colors is run on the remote computer, color does not change on the client display.

**Comment by koo5** [comment]
This is gonna be out of scope for xrandr-invert-colors, as vnc clients simply ignore the ramps setting. You would need a compositing manager (on either client or server), or to dedicate a screen to displaying a fullscreen vnc client..
Or try to tweak your vnc client, it might be easy in some cases: https://github.com/cair/pyVNC/blob/master/pyVNC/RFBToGUI.py

**Comment by zoltanp** [comment]
@koo5 Exactly, well said. 
xrandr-invert-colors cannot change colors on a client display of a remote connection. It has no means to do it.
